fix(data-table): Fix JS error in IE11 when setting multiple styles
Fixes following JS error

```
IE 11.0.0 (Windows 10.0.0) MDCDataTable Progress indicator Should hide progress indicator when hideProgress() called FAILED
    TypeError: Object doesn't support property or method 'assign'
    error properties: Object({ number: -2146827850 })
        at <Jasmine>
       at adapter.setProgressIndicatorStyles (packages/mdc-data-table/component.ts:201:9 <- packages/mdc-data-table/component.js:302:29)
       at MDCDataTableFoundation.prototype.showProgress (packages/mdc-data-table/foundation.ts:271:5 <- packages/mdc-data-table/foundation.js:791:21)
```

PiperOrigin-RevId: 321231202